// AUTO-GENERATED by scripts/prepare-valorant-assets.ts — do not edit by hand.
import type { MapAssetEntry } from "./map-assets"

export const MAP_ASSET_MAP: Record<string, MapAssetEntry> = {
  "abyss": { name: "Abyss", thumb: "/valorant/maps/thumb/abyss.webp", banner: "/valorant/maps/banner/abyss.webp", card: "/valorant/maps/card/abyss.webp" },
  "ascent": { name: "Ascent", thumb: "/valorant/maps/thumb/ascent.webp", banner: "/valorant/maps/banner/ascent.webp", card: "/valorant/maps/card/ascent.webp" },
  "bind": { name: "Bind", thumb: "/valorant/maps/thumb/bind.webp", banner: "/valorant/maps/banner/bind.webp", card: "/valorant/maps/card/bind.webp" },
  "breeze": { name: "Breeze", thumb: "/valorant/maps/thumb/breeze.webp", banner: "/valorant/maps/banner/breeze.webp", card: "/valorant/maps/card/breeze.webp" },
  "corrode": { name: "Corrode", thumb: "/valorant/maps/thumb/corrode.webp", banner: "/valorant/maps/banner/corrode.webp", card: "/valorant/maps/card/corrode.webp" },
  "fracture": { name: "Fracture", thumb: "/valorant/maps/thumb/fracture.webp", banner: "/valorant/maps/banner/fracture.webp", card: "/valorant/maps/card/fracture.webp" },
  "haven": { name: "Haven", thumb: "/valorant/maps/thumb/haven.webp", banner: "/valorant/maps/banner/haven.webp", card: "/valorant/maps/card/haven.webp" },
  "icebox": { name: "Icebox", thumb: "/valorant/maps/thumb/icebox.webp", banner: "/valorant/maps/banner/icebox.webp", card: "/valorant/maps/card/icebox.webp" },
  "lotus": { name: "Lotus", thumb: "/valorant/maps/thumb/lotus.webp", banner: "/valorant/maps/banner/lotus.webp", card: "/valorant/maps/card/lotus.webp" },
  "pearl": { name: "Pearl", thumb: "/valorant/maps/thumb/pearl.webp", banner: "/valorant/maps/banner/pearl.webp", card: "/valorant/maps/card/pearl.webp" },
  "split": { name: "Split", thumb: "/valorant/maps/thumb/split.webp", banner: "/valorant/maps/banner/split.webp", card: "/valorant/maps/card/split.webp" },
  "sunset": { name: "Sunset", thumb: "/valorant/maps/thumb/sunset.webp", banner: "/valorant/maps/banner/sunset.webp", card: "/valorant/maps/card/sunset.webp" },
}
